# GitHub Actionså·¥ä½œæµï¼šVercelé¢„è§ˆéƒ¨ç½²
# æ­¤å·¥ä½œæµåœ¨åˆ›å»ºPull Requestæ—¶è‡ªåŠ¨è§¦å‘ï¼Œå°†ä»£ç éƒ¨ç½²åˆ°Vercelè¿›è¡Œé¢„è§ˆ
name: GitHub Actions Preview Deployment

# è§¦å‘æ¡ä»¶ï¼šå½“æœ‰Pull Requestäº‹ä»¶æ—¶æ‰§è¡Œ
on:
  pull_request_target:
    types: [opened]


   
# å·¥ä½œä»»åŠ¡å®šä¹‰
jobs:
  # éƒ¨ç½²é¢„è§ˆä»»åŠ¡
  Deploy-Preview:
    # è¿è¡Œç¯å¢ƒï¼šä½¿ç”¨æœ€æ–°ç‰ˆUbuntu
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # æ­¥éª¤1ï¼šæ£€å‡ºä»£ç ä»“åº“
      - uses: actions/checkout@v3
      - name: write 
        run: |
          echo "VERCEL_ORG_ID=$VERCEL_ORG_ID" >> $GITHUB_ENV
      # åœ¨Githubä»£ç æä»·å¤„å…è®¸è¯„è®º
      - name: Enable PR comments
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ğŸ‰ æ„Ÿè°¢æ‚¨æäº¤æ‹‰å–è¯·æ±‚ï¼æ‚¨çš„è´¡çŒ®å¯¹æˆ‘ä»¬è‡³å…³é‡è¦ã€‚
            æˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œå®¡æ ¸ã€‚å¦‚æœæ‚¨æœ‰ä»»ä½•é—®é¢˜ï¼Œè¯·éšæ—¶æå‡ºã€‚

